name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: my-website/package-lock.json  # Specify the path to package-lock.json

      - name: Install dependencies
        working-directory: ./my-website  # Set working directory for this step
        run: npm ci

      - name: Build website
        working-directory: ./my-website  # Set working directory for this step
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-website/build  # Specify the build output directory
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
